### PR TITLE
Kpg/first run extended

### LINKED ISSUE #160: New local branch fails to load Gradle because of git command
We pull git tags for version managers that use git, but it happens while Gradle is loading. That will fail for new repos or new branches without remotes. This previously resulted in a warning but was changed to fix a different bug.

### PR DESCRIPTION
**Pull request by kpgalligan**
Fixes #160 
Merged #159 and #157

### CODE REVIEW

File: kmmbridge/src/main/kotlin/versionmanager/GitTagBasedVersionManager.kt [hunk 1]
```diff
@@ -14,18 +14,26 @@
...
 
-        // Need to make sure we have all the tags. This may need to be configurable in the future for
-        // more complex git setups. If call fails, we'll get a warning but keep going.
-        project.procRunFailLog("git", "pull", "--tags")
+        // Need to make sure we have all the tags. If no tags, we don't continue (but don't fail)
+        // This will usually happen when doing local dev.
+        try {
+            project.procRunFailThrow("git", "pull", "--tags")
+        } catch (e: ProcOutputException) {
+            val localOk = e.output.any { it.contains("There is no tracking information for the current branch") }
```
Comment (russhwolf) [inline kmmbridge/src/main/kotlin/versionmanager/GitTagBasedVersionManager.kt:28]: This feels really brittle, but probably ok for now. Can we ask git if there's a tracked branch instead?

Another alternative I want to think through (for later) is if it makes more sense to only ever push to a specific predefined branch instead of pushing to whatever the current branch is.

**Review by russhwolf — APPROVED** [review]

File: kmmbridge/src/main/kotlin/versionmanager/VersionManager.kt [hunk 2]
```diff
@@ -26,4 +26,6 @@ interface VersionManager {
      * Called after dependency managers are done.
      */
     fun recordVersion(project: Project, versionString: String)
-}
\ No newline at end of file
+}
+
+class VersionException(val localDevOk:Boolean, message: String?): Exception(message)
```
[the remark this answers is not in the document]
Comment (kpgalligan) [reply kmmbridge/src/main/kotlin/versionmanager/VersionManager.kt:31]: "If you're doing local dev, this error is OK"

File: kmmbridge/src/main/kotlin/versionmanager/GitTagBasedVersionManager.kt (hunk 1 above)
Comment (kpgalligan) [reply kmmbridge/src/main/kotlin/versionmanager/GitTagBasedVersionManager.kt:28]: I'd say it's brittle-ish, but the point is to distinguish what we'll log to info vs warning. No outcome results in an actual error. just no tasks registered. While I don't think it's the best, the stakes are low.

> Another alternative I want to think through (for later) is if it makes more sense to only ever push to a specific predefined branch instead of pushing to whatever the current branch is.

Not sure what you mean here, and this is pulling anyway. The tags come from all branches, which seems weird, but that's what happens.

Comment (kpgalligan) [reply kmmbridge/src/main/kotlin/versionmanager/GitTagBasedVersionManager.kt:28]: Oh, you mean trying to pull tags from, maybe, main even if you're not in main? Maybe. I just wanted to do something that'll work for now. The complication is we need the version during analysis, but that breaks in the wrong branch. If we set versions in a totally different way, this could be avoided directly, but not "right now" discussion.
